services:
  wuzapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"  # Use expose instead of ports for Coolify
    environment:
      - WUZAPI_ADMIN_TOKEN=${WUZAPI_ADMIN_TOKEN}
      - DB_USER=${DB_USER:-wuzapi}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-wuzapi}
      - DB_HOST=db
      - DB_PORT=5432
      - TZ=${TZ:-America/Los_Angeles}
      - WEBHOOK_FORMAT=${WEBHOOK_FORMAT:-json}
      - SESSION_DEVICE_NAME=${SESSION_DEVICE_NAME:-WuzAPI}
      - RABBITMQ_URL=${RABBITMQ_URL:-}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE:-whatsapp_events}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wuzapi-network
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=wuzapi"
      - "coolify.port=8080"
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-wuzapi}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-wuzapi}
    # No ports exposed - internal network only
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wuzapi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-wuzapi}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
      
networks:
  wuzapi-network:
    driver: bridge

volumes:
  db_data: