services:
  wuzapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WUZAPI_PORT:-8080}:8080"  # Coolify will handle external routing
    environment:
      - WUZAPI_ADMIN_TOKEN=${WUZAPI_ADMIN_TOKEN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
      - TZ=${TZ:-America/Sao_Paulo}
      - WEBHOOK_FORMAT=${WEBHOOK_FORMAT:-json}
      - SESSION_DEVICE_NAME=${SESSION_DEVICE_NAME:-WuzAPI}
      - RABBITMQ_URL=${RABBITMQ_URL:-}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE:-whatsapp_events}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wuzapi-network
    restart: on-failure

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "${DB_EXTERNAL_PORT:-5432}:5432"  # Not needed for Coolify - internal network only
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wuzapi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
      
networks:
  wuzapi-network:
    driver: bridge

volumes:
  db_data: